### ISSUE TITLE
Resource not found: The following package was not found in <arg name="world_name" value="$(find PathPlanning-for-DifferentialDriveRobot)/worlds/map.world"/>: Pa

### ISSUE THREAD

**Issue by emmmosusj** [Rishabh96M/PathPlaning#1]
Resource not found: The following package was not found in <arg name="world_name" value="$(find PathPlanning-for-DifferentialDriveRobot)/worlds/map.world"/>: Pa

**Comment by Rishabh96M** [comment]
map.world file is present in this repository, you have to copy it to the catkin workspace you created. 

I have given detailed steps in README.md, kindly follow that.

**Comment by harvey-yeh** [comment]
Excuse me, I follow the steps, and have the same problem.
the error said

Resource not found: The following package was not found in <arg name="world_name" value="$(find PathPlanning-for-DifferentialDriveRobot)/worlds/map.world"/>: PathPlanning-for-DifferentialDriveRobot
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/harvey/catkin_ws/src
ROS path [2]=/opt/ros/noetic/share
The traceback for the exception was written to the log file
